LBHackney-IT/housing-needs-single-view-api

- lib/Constants.js
- lib/backends/UHT-Contacts/index.js
- lib/backends/UHT-Contacts/sql/fetchActionDiariesNotes.sql
Co-authored-by: Maria <maria@madetech.com>
> Add Action Diaries Notes for UHT

- api/lib/gateways/UHT-HousingRegister/UHTHousingRegisterSearchGateway.js
- api/lib/gateways/UHT-HousingRegister/sql/fetchCustomer.sql
- api/lib/gateways/UHT-HousingRegister/sql/fetchCustomerNotes.sql
- api/lib/gateways/UHT-HousingRegister/sql/searchCustomersBase.sql
- api/test/gateways/Academy-CouncilTax/AcademyCouncilTaxSearchGateway.test.js
- api/test/gateways/UHT-Contacts/UHTContactsSearchGateway.test.js
- api/test/gateways/UHT-HousingRegister/UHTHousingRegisterSearchGateway.test.js
Separate the UHT Housing Register Gateway
> UHT housing register search gateway

- api/lib/JigsawUtils.js
- api/lib/gateways/Jigsaw/JigsawSearchGateway.js
- api/test/gateways/Jigsaw/JigsawSearchGateway.test.js
Add Jigsaw Gateway
Extract JigsawUtils for Jigsaw Get Requests
> Jigsaw search gateway

- api/lib/gateways/Academy-Benefits/Search.js
- api/lib/gateways/Academy-CouncilTax/Search.js
- api/lib/gateways/SingleView/Search.js
- api/lib/gateways/UHT-Contacts/Search.js
- api/lib/gateways/UHT-HousingRegister/Search.js
- api/lib/gateways/UHW/Search.js
Trimmed first names and last names to remove spaces, as extra spaces affected the search results.
> Fix search with spaces issue

- api/lib/gateways/Academy-Benefits/FetchDocuments.js
- api/lib/gateways/Academy-Benefits/FetchNotes.js
- api/lib/gateways/Academy-CouncilTax/FetchDocuments.js
- api/lib/gateways/Academy-CouncilTax/FetchNotes.js
- api/lib/gateways/Jigsaw/FetchDocuments.js
- api/lib/gateways/Jigsaw/FetchNotes.js
- api/lib/gateways/UHT-Contacts/FetchNotes.js
- api/lib/gateways/UHT-HousingRegister/FetchNotes.js
- api/lib/gateways/UHW/FetchDocuments.js
- api/lib/gateways/UHW/FetchNotes.js
- api/lib/libDependencies.js
- api/lib/use-cases/FetchDocuments.js
- api/lib/use-cases/FetchNotes.js
- api/test/gateways/Academy-Benefits/FetchDocuments.test.js
- api/test/gateways/Academy-Benefits/FetchNotes.test.js
- api/test/gateways/Academy-CouncilTax/FetchDocuments.test.js
- api/test/gateways/Academy-CouncilTax/FetchNotes.test.js
- api/test/gateways/Jigsaw/FetchDocuments.test.js
- api/test/gateways/Jigsaw/FetchNotes.test.js
- api/test/gateways/UHT-Contacts/FetchNotes.test.js
- api/test/gateways/UHT-HousingRegister/FetchNotes.test.js
- api/test/gateways/UHW/FetchDocuments.test.js
- api/test/gateways/UHW/FetchNotes.test.js
- api/test/use-cases/FetchDocuments.test.js
- api/test/use-cases/FetchNotes.test.js
Gateways would only return documents and notes for 1 ID in the system.
Before:
- Use case passes in customer ID from SV
- Gateway gets the remote_id from SV and executes fetch/SQL command once
After:
- Use case gets all the remote IDs and map gateway calls using each ID
- Gateways get called multiple times with different IDs (for the same system)
- Use case concatenates all the results
https://beta.singleview.hackney.gov.uk/customers/998/view
https://beta.singleview.hackney.gov.uk/customers/975/view
https://beta.singleview.hackney.gov.uk/customers/886/view (If you search for academy-benefits more search results pop up on the new version)
> Fetch all the documents

- .prettierrc
- api/index.js
- readme.md
Basic readme with instructions how to get the local environment up and running
> add basic readme

- api/lib/backends/UHT-Contacts/FetchRecord.js
- api/lib/backends/UHT-Contacts/sql/fetchCustomer.sql
Queries for payment reference to be displayed in system IDs
> Add query for payment reference

- api/lib/gateways/UHT-HousingRegister/FetchRecord.js
- api/lib/gateways/UHT-HousingRegister/sql/fetchCustomer.sql
- api/test/lib/MergeResponses.test.js
- docker-compose.yml
- schema.sql
In this PR I pulled bedroom requirements field from UHT and is now ready to be displayed.
> Bedroom requirements

- api/lib/Constants.js
- api/lib/gateways/UHT-HousingRegister/FetchRecord.js
- api/lib/gateways/UHT-HousingRegister/sql/fetchCustomer.sql
- api/test/lib/MergeResponses.test.js
In this PR I added application status to housing register and updated the tests to check for it.
> Application status

- .circleci/config.yml
- .env.test
- Dockerfile
- Dockerfile.testenv
- docker-compose.yml
- package.json
as we run our tests in docker, we don't need the executor to run the tests. 
so for tests we just bring up a machine box and let the docker image run there
> Integration tests docker machine

- api/test/integration/first.test.js
- api/test/sql/UHT/test_schema.sql
- docker-compose.yml
Creates all the mssql tables that get queried by 'search' use case.
Clears up related errors and reduces log significantly.
> Add more schema

- api/lib/Constants.js
- api/test/integration/first.test.js
- package.json
- readme.md
This PR updates the integration tests so they can pass locally. We've also updated the documentation on how to run the integration tests locally.
> Integration tests

- jigsaw/gateways/FetchDocumentMetadata.js
Fetch Jigsaw metadata was using wrong env vars
> Fix env vars for jigsaw

- .circleci/config.yml
- api/test/gateways/Academy-Benefits/FetchRecord.test.js
- api/test/gateways/Academy-CouncilTax/FetchRecord.test.js
- api/test/gateways/Jigsaw/FetchRecord.test.js
- api/test/gateways/UHT-Contacts/FetchRecord.test.js
- api/test/gateways/UHT-HousingRegister/FetchRecord.test.js
- api/test/gateways/UHW/FetchRecord.test.js
- api/test/integration/TestUtils.js
- api/test/integration/api.test.js
- api/test/integration/fetchRecord.test.js
- docker-compose.yml
- serverless-jigsaw-docs.yml
- added integration test utils 
- added unit tests for each fetch record in every gateway
- added timezones to integration test containers
> Fetch record tests

- api/lib/gateways/Vulnerabilities/VulnerabilitiesApi.js
- api/test/gateways/Vulnerabilities/VulnerabilitiesApi.test.js
WHAT
Update the vulnerabilities urls
> Update vulnerabilities urls

- api/index.js
- api/lib/gateways/Vulnerabilities/VulnerabilitiesApi.js
- api/test/gateways/Vulnerabilities/VulnerabilitiesApi.test.js
WHAT
I want my snapshot id to return as snapshotId
> Fix snapshot ids

- api/lib/gateways/Vulnerabilities/VulnerabilitiesApi.js
- api/lib/use-cases/CreateVulnerabilitySnapshot.js
- api/test/gateways/Vulnerabilities/VulnerabilitiesApi.test.js
- api/test/use-cases/CreateVulnerabilitySnapshot.test.js
WHAT
Add the dob when creating a vulnerability snapshot
> Add dob to vulnerability snapshot

- api/lib/gateways/Academy-Benefits/Search.js
- api/lib/gateways/Academy-Benefits/SearchAPI.js
- api/lib/gateways/Academy-Benefits/SearchDb.js
- api/lib/libDependencies.js
- api/lib/logger.js
- api/test/gateways/Academy-Benefits/Search.test.js
- api/test/gateways/Academy-Benefits/SearchAPI.test.js
- api/test/gateways/Academy-Benefits/SearchDb.test.js
- api/test/logger.test.js
- serverless-api.yml
When searching Academy, search both the DB and API then log the comparison between results but still return the results from the DB.
> Search academy API as well as the database and compare results

- api/lib/gateways/Academy-Benefits/SearchAPI.js
- api/test/gateways/Academy-Benefits/SearchAPI.test.js
when searching academy
Also changed the Academy API response to return postcode as one word.
> Get address from the correct field in the Academy API response

- api/lib/gateways/Academy-Benefits/FetchCustomerAPI.js
- api/lib/gateways/Academy-Benefits/FetchCustomerDB.js
- api/lib/gateways/Academy-Benefits/FetchRecord.js
- api/lib/gateways/Academy-Benefits/Search.js
- api/lib/gateways/Academy-Benefits/SearchAPI.js
- api/lib/gateways/Academy-Benefits/SearchDb.js
- api/lib/libDependencies.js
- api/lib/logger.js
- api/package-lock.json
- api/test/gateways/Academy-Benefits/FetchCustomerAPI.test.js
- api/test/gateways/Academy-Benefits/FetchCustomerDb.test.js
- api/test/gateways/Academy-Benefits/FetchRecord.test.js
- package-lock.json
Fetch customer record from Academy API and compare with Academy DB, then log an differences and return record from the database.
> Fetch Customer record from Academy API, compare with DB and log results

- api/index.js
- api/lib/gateways/Tenancies/TenanciesApi.js
- api/lib/libDependencies.js
- api/lib/use-cases/SearchTenancies.js
- api/test/FakePlatformApis.js
- api/test/gateways/Tenancies/TenanciesApi.test.js
- api/test/integration/searchTenancies.test.js
- api/test/use-cases/SearchTenancies.test.js
- serverless-api.yml
- test_env
- Adds an endpoint to search tenancies by address.
- Option to filter tenancies by freeholder or leaseholder agreements.
- Option to filter by former or current tenancies.
- Uses the Tenancy API to retrieve the tenancies.
> Search Tenancies

- api/lib/JigsawUtils.js
- api/test/FakeJigsawAndW2.js
Jigsaw have update their login endpoint which was breaking our integration. This updates to match
> Update method of extracting the jigsaw token

- api/index.js
- api/lib/gateways/UHT-Tenancies/FetchTenants.js
- api/lib/gateways/UHT-Tenancies/sql/fetchTenants.sql
- api/lib/libDependencies.js
- api/lib/use-cases/FetchCautionaryAlerts.js
- api/lib/use-cases/FetchTenancy.js
- api/test/use-cases/FetchTenancy.test.js
**What?**
Fetch cautionary alerts for each person within a tenancy. 
**Why?**
To provide more information about the tenants
**Anything else?**
Add back fetchTenants gateway that fetches tenancy records directly from UHT. 
Compare and merge these records with the ones that are coming from MAT API, because they would not always match.
> Sv 136/cautionary alerts

- api/lib/gateways/CautionaryAlerts/CautionaryAlertsApi.js
- api/test/gateways/CautionaryAlerts/CautionaryAlertsApi.test.js
**What?**
Fix the return of the cautionary alerts and some linting
> Fix the return of the cautionary alerts

- serverless-api.yml
- serverless-jigsaw-docs.yml
Also make the groups match for the jigsaw api
> Add dev auth groups to serverless yml

- api/index.js
- api/lib/gateways/MaT-Service-API/FetchAreaPatch.js
- api/lib/libDependencies.js
- api/lib/use-cases/FetchAreaPatch.js
- api/test/gateways/MaT-Service-API/FetchAreaPatch.test.js
- api/test/use-cases/FetchAreaPatch.test.js
What?
- Added a gateway and a use-case for fetching area and patch and officer name
Why?
- To display area and patch and officer name in Single View
> Area and patch

- api/lib/gateways/MaT-Service-API/FetchTasks.js
- api/lib/libDependencies.js
- api/lib/use-cases/FetchTenancy.js
- api/test/gateways/MaT-Service-API/FetchTasks.test.js
- api/test/use-cases/FetchTenancy.test.js
- Added gateway and use-case for fetching tasks by tag_ref
- Added unit tests
> Sv 140/get task by tag ref

- api/index.js
- api/lib/gateways/MRA-API/FetchTransactions.js
- api/lib/gateways/UHT-Tenancies/FetchTenancy.js
- api/lib/gateways/UHT-Tenancies/sql/fetchTenancy.sql
- api/lib/libDependencies.js
- api/lib/use-cases/FetchTransactions.js
- api/test/gateways/MRA-API/FetchTransactions.test.js
- api/test/use-cases/FetchTransactions.test.js
- serverless-api.yml
- Added gateway, use-case and endpoint to fetch rent transactions
- Added unit-tests
> Sv 137/rent details

- api/lib/gateways/MRA-API/FetchTransactions.js
- Remove the -1 multiplication for balance in rent transactions
> Update 'balance' in rent transactions

- api/index.js
- api/lib/Utils.js
- Added a function to change the birth date of 01-01-1900 to undefined
> Add function to transform birth date
